name: Build FFmpeg for Android

on:
  workflow_dispatch:
    inputs:
      sdk-version:
        description: "Android SDK version"
        required: true
        default: "31"
        type: string
      ndk-version:
        description: "Android NDK version"
        required: true
        default: "r28c"
        type: string
      ffmpeg-version:
        description: "FFmpeg version"
        required: true
        default: "n8.0"
        type: string
      ffmpeg-prefix:
        description: "Prefix"
        required: true
        default: "ffprobe"
        type: string
      additional-dependencies:
        description: "Additional dependencies"
        required: false
        default: "libdav1d-dev libvpx-dev libx264-dev libx265-dev libnuma-dev libtheora-dev"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Clone FFmpeg
        run: |
          git clone --branch ${{ github.event.inputs.ffmpeg-version }} \
            --single-branch \
            --depth=1 \
            https://github.com/FFmpeg/FFmpeg ffmpeg
        
      - name: Setup Android NDK
        uses: HoshinoSuzumi/setup-ndk@v1
        with:
          ndk-version: ${{ github.event.inputs.ndk-version }}
          
      - name: Install required dependencies
        run: |
          sudo apt-get update -qq && sudo apt-get -y install \
            build-essential \
            pkg-config \
            yasm \
            nasm \
            autoconf \
            automake \
            libtool
            
      - name: Install additional dependencies
        run: |
          sudo apt-get -y install -qq \
            ${{ github.event.inputs.additional-dependencies }}

      - name: Configure environment 
        run: |
          echo "BUILD_DIR=$GITHUB_WORKSPACE/build" >> $GITHUB_ENV
          echo "BUILD_DIR_FFMPEG=$BUILD_DIR/${{ github.event.inputs.ffmpeg-prefix }}" >> $GITHUB_ENV
          
          echo "TARGET_API_LEVEL=${{ github.event.inputs.sdk-version }}" >> $GITHUB_ENV
          echo "TARGET_ARCH=aarch64" >> $GITHUB_ENV
          echo "TARGET_TRIPLE=aarch64-linux-android" >> $GITHUB_ENV
          echo "TARGET_PLATFORM=android-$TARGET_API_LEVEL" >> $GITHUB_ENV
          
          echo "NDK_TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV
          echo "SYSROOT=$NDK_TOOLCHAIN/sysroot" >> $GITHUB_ENV
          
          echo "CC=$NDK_TOOLCHAIN/bin/${TARGET_TRIPLE}${TARGET_API_LEVEL}-clang" >> $GITHUB_ENV
          echo "CXX=$NDK_TOOLCHAIN/bin/${TARGET_TRIPLE}${TARGET_API_LEVEL}-clang++" >> $GITHUB_ENV
          echo "LD=$NDK_TOOLCHAIN/bin/ld" >> $GITHUB_ENV
          echo "AR=$NDK_TOOLCHAIN/bin/llvm-ar" >> $GITHUB_ENV
          echo "AS=$CC" >> $GITHUB_ENV
          echo "NM=$NDK_TOOLCHAIN/bin/llvm-nm" >> $GITHUB_ENV
          echo "RANLIB=$NDK_TOOLCHAIN/bin/llvm-ranlib" >> $GITHUB_ENV
          echo "STRIP=$NDK_TOOLCHAIN/bin/llvm-strip" >> $GITHUB_ENV
          
      - name: Build FFmpeg
        run: |
          cd ffmpeg
          
          # Set environment variables for the configure script
          export PATH="$NDK_TOOLCHAIN/bin:$PATH"
          
          ./configure \
            --prefix="$BUILD_DIR_FFMPEG" \
            --enable-cross-compile \
            --target-os=android \
            --arch=$TARGET_ARCH \
            --sysroot="$SYSROOT" \
            --cc="$CC" \
            --cxx="$CXX" \
            --ld="$LD" \
            --ar="$AR" \
            --as="$AS" \
            --nm="$NM" \
            --ranlib="$RANLIB" \
            --strip="$STRIP" \
            --extra-cflags="-O3 -fPIC"
            --enable-shared \
            --disable-static \
            --disable-vulkan \
            --enable-small \
            --disable-ffplay \
            --disable-ffmpeg \
            --enable-ffprobe \
            --disable-doc \
            --disable-avdevice \
            --disable-swresample \
            --enable-gpl \
            --disable-encoders \
            --disable-hwaccels \
            --disable-muxers \
            --disable-bsfs \
            --disable-protocols \
            --disable-indevs \
            --disable-outdevs \
            --disable-devices \
            --enable-protocol=file \
            --disable-debug \
            --enable-libdav1d \
            --enable-libvpx \
            --enable-libx264 \
            --enable-libx265 \
            --enable-libtheora \
            
          make -j$(nproc)
          make install
          
      - name: Upload FFprobe binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.ffmpeg-prefix }}
          path: ${{ env.BUILD_DIR_FFMPEG }}
